import { useEffect, useState } from 'react'
import { insforge, type Movie } from './insforge'
import { TAB_ENTRIES } from './modules.generated'
import { AtSign, Code2, ExternalLink, MessageCircle, PanelLeftClose, PanelLeftOpen, PlayCircle, Settings } from 'lucide-react'
import { signIn, startSessionKeeper } from './session'
import { ComfyJobsPanel } from './ComfyJobsPanel'
import { ModelPicker } from './ui/ModelPicker'
import { SettingsPanel } from './SettingsPanel'
import { triggerFlow, parseFlowJson } from './flowise'

// What 15-Delete-Movie reports before anything is removed.
type DeleteSurvey = {
  movie: string
  slug: string
  rows: Record<string, number>
  storageObjects: number
  bucket: string
  comfyFolders: { path: string; exists: boolean | null; note?: string }[]
}
import { Select } from './ui/Select'
import './App.css'
import './theme.css'
// Skin, last on purpose: it is unlayered and overrides the layered sheets above.
import './copper.css'
import { ThemeToggle } from './ui/ThemeToggle'
import { ImagePreview } from './ui/ImagePreview'

// Each tab carries its own glyph so the sidebar reads as icons + labels
// rather than a wall of text. Flat lucide strokes, not emoji.
// The tabs this install has. Generated by install/lib/write-registry.js from
// the modules that were installed, so a tab exists here only when its panel
// was copied in - which is what keeps a small install small.
const TABS = TAB_ENTRIES

// Any installed tab's id. It is a plain string because the set is decided at
// install time, not at compile time.
type Tab = string

const DEFAULT_TAB: Tab = 'documents'

// The open tab lives in the URL hash rather than component state alone, so a
// refresh comes back to the page you were on. Treating the hash as the single
// source of truth - clicks write to it, a listener reads back out - also means
// the browser's Back and Forward buttons move between tabs for free.
//
// An unknown or absent hash falls back to the default rather than rendering
// nothing, so a stale bookmark from a renamed tab still opens the app.
function readTabFromHash(): Tab {
  const id = window.location.hash.replace(/^#\/?/, '')
  return TABS.some((t) => t.id === id) ? (id as Tab) : DEFAULT_TAB
}

function App() {
  const [movies, setMovies] = useState<Movie[]>([])
  const [movieId, setMovieId] = useState<string>('')
  const [tab, setTab] = useState<Tab>(readTabFromHash)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [showNewMovie, setShowNewMovie] = useState(false)
  const [newMovieTitle, setNewMovieTitle] = useState('')
  const [creatingMovie, setCreatingMovie] = useState(false)
  const [deleting, setDeleting] = useState<'idle' | 'surveying' | 'confirm' | 'deleting'>('idle')
  // Copying a film into another medium. The style is chosen BEFORE the copy,
  // because it is stamped onto the new characters, scenes and props as they are
  // written - it is what every prompt is then rebuilt on top of.
  const [copying, setCopying] = useState<'idle' | 'form' | 'working'>('idle')
  const [copyTitle, setCopyTitle] = useState('')
  const [copyStyle, setCopyStyle] = useState('photographic')
  const [deleteSurvey, setDeleteSurvey] = useState<DeleteSurvey | null>(null)
  const [deleteTyped, setDeleteTyped] = useState('')
  const [settingsOpen, setSettingsOpen] = useState(false)
  const [railed, setRailed] = useState(() => {
    try {
      return localStorage.getItem('sidebar-railed') === '1'
    } catch {
      // Private windows and blocked site data throw on access, not on read.
      return false
    }
  })

  function toggleRail() {
    setRailed((v) => {
      const next = !v
      try {
        localStorage.setItem('sidebar-railed', next ? '1' : '0')
      } catch {
        /* Not worth failing the click over. */
      }
      return next
    })
  }

  useEffect(() => {
    const sync = () => setTab(readTabFromHash())
    window.addEventListener('hashchange', sync)
    return () => window.removeEventListener('hashchange', sync)
  }, [])

  useEffect(() => {
    async function init() {
      // Single-operator tool: sign in as the one fixed local account so
      // storage RLS (authenticated-only, see migration
      // fix-storage-rls-use-authenticated) allows uploads.
      const authError = await signIn()
      if (authError) {
        setError(`Sign-in failed: ${authError}`)
        setLoading(false)
        return
      }

      const { data, error } = await insforge.database
        .from('movies')
        .select('*')
        .order('created_at', { ascending: true })
      if (error) setError(error.message)
      else {
        const list = (data ?? []) as Movie[]
        setMovies(list)
        const active = list.find((m) => m.is_active)
        if (active) setMovieId(active.id)
        else if (list.length > 0) setMovieId(list[0].id)
      }
      setLoading(false)
    }
    init()
    return startSessionKeeper()
  }, [])

  const movie = movies.find((m) => m.id === movieId)

  async function handleMovieChange(newMovieId: string) {
    setMovieId(newMovieId)
    setMovies((prev) => prev.map((m) => ({ ...m, is_active: m.id === newMovieId })))

    // Selecting a movie here IS how the pipeline knows which movie is
    // "active" - the Flowise flows look this up at runtime instead of
    // having a movie hardcoded. Deactivate whichever was active, then
    // activate the newly selected one (two steps so the partial unique
    // index on is_active is never asked to hold two true rows at once).
    await insforge.database.from('movies').update({ is_active: false }).eq('is_active', true)
    await insforge.database.from('movies').update({ is_active: true }).eq('id', newMovieId)
  }

  // Deleting is two steps on purpose: the flow first REPORTS everything that
  // would go, and only deletes once the exact title is typed back. There is no
  // undo - it removes renders, panoramas and splats as well as rows.
  // Copy the film, not its pictures.
  //
  // The new movie is never made active: nearly every flow finds its movie by
  // is_active, so a copy that activated itself would quietly redirect work away
  // from whatever is being made right now. You switch to it when you are ready.
  async function handleCopyMovie(e: React.FormEvent) {
    e.preventDefault()
    if (!movie) return
    const flowId = import.meta.env.VITE_COPY_MOVIE_ID
    if (!flowId) {
      setError('VITE_COPY_MOVIE_ID is not set in .env - restart the dev server after adding it.')
      return
    }
    setCopying('working')
    setError(null)
    const res = parseFlowJson<{
      action: string
      movieId?: string
      title?: string
      counts?: Record<string, unknown>
      error?: string
    }>(
      await triggerFlow(flowId, {
        movieId: movie.id,
        title: copyTitle.trim() || `${movie.title} (copy)`,
        renderStyle: copyStyle,
        // Straight to rendering: the shot list comes across whole, so the copy
        // starts where this film got to rather than re-planning coverage. The
        // shimmy inserts, the sizes and the per-shot wardrobe are decisions
        // about the FILM, and it is the same film.
        includeShots: true
      })
    )
    if (!res.ok || res.data.action !== 'copied') {
      setError(res.ok ? (res.data.error ?? res.data.action) : res.message)
      setCopying('form')
      return
    }
    const { data: fresh } = await insforge.database
      .from('movies')
      .select('*')
      .order('created_at', { ascending: false })
    setMovies((fresh ?? []) as Movie[])
    setCopying('idle')
    setCopyTitle('')
    const counts = res.data.counts ?? {}
    const what = Object.entries(counts)
      .filter(([k]) => k !== 'plan')
      .map(([k, v]) => `${v} ${k}`)
      .join(', ')
    setError(
      `Copied as "${res.data.title}" (${copyStyle}): ${what}. No pictures came across - ` +
        'generate the character references, panoramas and prop sheets, then render. ' +
        'Switch to it in the picker above when you are ready.'
    )
  }

  async function handleDeleteSurvey() {
    if (!movie) return
    setDeleting('surveying')
    setError(null)
    const res = parseFlowJson<{ willDelete: DeleteSurvey }>(
      await triggerFlow(import.meta.env.VITE_DELETE_MOVIE_ID, { movieId: movie.id })
    )
    if (!res.ok) {
      setError(res.message)
      setDeleting('idle')
      return
    }
    setDeleteSurvey(res.data.willDelete)
    setDeleteTyped('')
    setDeleting('confirm')
  }

  async function handleDeleteConfirm() {
    if (!movie) return
    setDeleting('deleting')
    setError(null)
    const res = parseFlowJson<{ action: string }>(
      await triggerFlow(import.meta.env.VITE_DELETE_MOVIE_ID, { movieId: movie.id, confirm: movie.title })
    )
    if (!res.ok) {
      setError(res.message)
      setDeleting('confirm')
      return
    }
    const remaining = movies.filter((m) => m.id !== movie.id)
    setMovies(remaining)
    setDeleteSurvey(null)
    setDeleting('idle')
    if (remaining.length > 0) await handleMovieChange(remaining[0].id)
    else setMovieId('')
  }

  async function handleCreateMovie(e: React.FormEvent) {
    e.preventDefault()
    const title = newMovieTitle.trim()
    if (!title) return

    setCreatingMovie(true)
    setError(null)
    const { data, error } = await insforge.functions.invoke('create-movie', { body: { title } })
    setCreatingMovie(false)

    if (error) {
      setError(error.message)
      return
    }

    const created = (data as { movie: Movie }).movie
    setMovies((prev) => [...prev, created])
    setNewMovieTitle('')
    setShowNewMovie(false)
    // Creating a movie is treated the same as selecting it - you presumably
    // want to start working on it right away.
    await handleMovieChange(created.id)
  }

  return (
    <div className={'app' + (railed ? ' railed' : '')}>
      <ImagePreview />
      <aside className="sidebar">
        <div className="brand">
          <span className="brand-mark" />
          <span className="brand-name">AI Movie Pipeline</span>
          <button
            type="button"
            className="rail-toggle"
            onClick={toggleRail}
            title={railed ? 'Expand the menu' : 'Collapse the menu'}
            aria-label={railed ? 'Expand the menu' : 'Collapse the menu'}
            aria-expanded={!railed}
          >
            {railed ? <PanelLeftOpen size={16} /> : <PanelLeftClose size={16} />}
          </button>
        </div>
        {movie && (
          <nav className="side-nav">
            {TABS.map((t) => (
              <button
                key={t.id}
                className={tab === t.id ? 'active' : ''}
                onClick={() => {
                  window.location.hash = t.id
                }}
                title={t.hint}
              >
                <t.Icon size={16} strokeWidth={1.9} />
                <span>{t.label}</span>
              </button>
            ))}
          </nav>
        )}

        {/* Footer, pinned to the foot of the nav. Placeholder hrefs - these are
            the links the design calls for, not routes that exist yet. */}
        <div className="site-footer">
          <a href="#contact">Contact info</a>
          <a href="#terms">
            Terms of service <ExternalLink size={11} />
          </a>
          <a href="#privacy">Privacy Policy</a>
          <div className="site-footer-social">
            <a href="#twitter" aria-label="Twitter"><AtSign size={19} /></a>
            <a href="#github" aria-label="GitHub"><Code2 size={19} /></a>
            <a href="#discord" aria-label="Discord"><MessageCircle size={19} /></a>
            <a href="#youtube" aria-label="YouTube"><PlayCircle size={19} /></a>
          </div>
          <p className="site-footer-copy">Copyright AI Movie Pipeline</p>
        </div>
      </aside>

      <div className="content">
      <header>
        <div className="movie-picker">
          <ComfyJobsPanel />
          {/* Which language model everything uses. Header rather than a settings
              page because it is switched often and applies to every tab. */}
          <ModelPicker />
          <ThemeToggle />
          {movies.length > 0 && (
            <Select
              value={movieId}
              onValueChange={handleMovieChange}
              items={movies.map((m) => ({ value: m.id, label: m.title }))}
              placeholder="Choose a movie"
            />
          )}
          {!showNewMovie ? (
            <>
              <button type="button" className="primary" onClick={() => setShowNewMovie(true)}>
                + New Movie
              </button>
              {movie && (
                <button
                  type="button"
                  className="danger"
                  disabled={deleting !== 'idle'}
                  onClick={handleDeleteSurvey}
                >
                  {deleting === 'surveying' ? 'Checking…' : 'Delete movie'}
                </button>
              )}
              {movie && copying === 'idle' && (
                <button
                  type="button"
                  onClick={() => {
                    setCopyTitle(`${movie.title} (live action)`)
                    setCopying('form')
                  }}
                  title="Makes the same film again in another medium: the script, scenes, cast, props, wardrobe, staging and the whole shot list come across. No pictures do - those are what you regenerate."
                >
                  Copy movie
                </button>
              )}
              {movie && copying !== 'idle' && (
                <form className="new-movie-form" onSubmit={handleCopyMovie}>
                  <input
                    type="text"
                    autoFocus
                    placeholder="New title"
                    value={copyTitle}
                    onChange={(e) => setCopyTitle(e.target.value)}
                    disabled={copying === 'working'}
                  />
                  <select
                    value={copyStyle}
                    onChange={(e) => setCopyStyle(e.target.value)}
                    disabled={copying === 'working'}
                    title="Chosen before the copy, because it is stamped onto the new characters, scenes and props as they are written - every prompt is then rebuilt on top of it."
                  >
                    <option value="photographic">Live action</option>
                    <option value="anime">Anime</option>
                    <option value="cartoon">Cartoon</option>
                    <option value="animated">3D animated</option>
                  </select>
                  <button type="submit" className="primary" disabled={copying === 'working'}>
                    {copying === 'working' ? 'Copying…' : 'Copy'}
                  </button>
                  <button type="button" onClick={() => setCopying('idle')} disabled={copying === 'working'}>
                    Cancel
                  </button>
                </form>
              )}
            </>
          ) : (
            <form className="new-movie-form" onSubmit={handleCreateMovie}>
              <input
                type="text"
                autoFocus
                placeholder="Movie title"
                value={newMovieTitle}
                onChange={(e) => setNewMovieTitle(e.target.value)}
              />
              <button type="submit" disabled={!newMovieTitle.trim() || creatingMovie}>
                {creatingMovie ? 'Creating…' : 'Create'}
              </button>
              <button
                type="button"
                onClick={() => {
                  setShowNewMovie(false)
                  setNewMovieTitle('')
                }}
              >
                Cancel
              </button>
            </form>
          )}
                  {/* What this install has, and what else it can have. A gear rather
              than a tab: it is about the app, not about a project. */}
          <button
            type="button"
            className={'settings-gear' + (settingsOpen ? ' is-open' : '')}
            title="Settings and modules"
            aria-label="Settings and modules"
            aria-pressed={settingsOpen}
            onClick={() => setSettingsOpen((v) => !v)}
          >
            <Settings size={16} strokeWidth={1.9} />
          </button>
</div>
      </header>

      {deleting === 'confirm' && deleteSurvey && (
        <div className="delete-confirm">
          <h3>Delete “{deleteSurvey.movie}” permanently?</h3>
          <p className="empty">This cannot be undone. Everything below is removed:</p>
          <ul>
            {Object.entries(deleteSurvey.rows)
              .filter(([, n]) => n > 0)
              .map(([table, n]) => (
                <li key={table}>
                  {n} {table.replace(/_/g, ' ')}
                </li>
              ))}
            {deleteSurvey.storageObjects > 0 && (
              <li>
                {deleteSurvey.storageObjects} uploaded file(s) in {deleteSurvey.bucket}
              </li>
            )}
            {deleteSurvey.comfyFolders
              .filter((f) => f.exists)
              .map((f) => (
                <li key={f.path}>
                  {f.path} — every rendered image and video in it
                </li>
              ))}
          </ul>
          {deleteSurvey.comfyFolders.some((f) => f.exists === null) && (
            <p className="error">
              ComfyUI folders could not be reached, so they will be left in place:{' '}
              {deleteSurvey.comfyFolders.map((f) => f.path).join(', ')}
            </p>
          )}
          <p className="empty">Type the title to confirm:</p>
          <input
            type="text"
            autoFocus
            placeholder={deleteSurvey.movie}
            value={deleteTyped}
            onChange={(e) => setDeleteTyped(e.target.value)}
          />
          <button
            type="button"
            className="danger"
            disabled={deleteTyped !== deleteSurvey.movie || (deleting as string) === 'deleting'}
            onClick={handleDeleteConfirm}
          >
            {(deleting as string) === 'deleting' ? 'Deleting…' : 'Delete permanently'}
          </button>
          <button
            type="button"
            onClick={() => {
              setDeleting('idle')
              setDeleteSurvey(null)
            }}
          >
            Cancel
          </button>
        </div>
      )}

      {loading && <p>Loading…</p>}
      {error && <p className="error">{error}</p>}

      {!loading && movies.length === 0 && (
        <p className="empty">No movies yet. Create one via the InsForge CLI or backend.</p>
      )}

      {movie && (
        <>

          {/* Every tab already carried a label and a one-line hint for its nav
              tooltip. Promoting them to a real page heading is what tells you
              which page you are on without reading the sidebar highlight. */}
          {(() => {
            const meta = TABS.find((t) => t.id === tab)
            if (!meta) return null
            // The tab's own glyph, repeated large. It ties the page to the row
            // you clicked in the sidebar, which a bare title does not.
            return (
              <div className="page-head">
                <span className="page-head-icon">
                  <meta.Icon size={20} strokeWidth={2} />
                </span>
                <div className="page-head-text">
                  {/* Split so the last word can carry the second colour, as in
                      the mockup's hand-painted two-tone lettering. CSS alone
                      cannot target a word. */}
                  <h1>
                    {meta.label.split(' ').map((w, i, all) =>
                      i === all.length - 1 ? (
                        <span className="tail" key={i}>
                          {w}
                        </span>
                      ) : (
                        <span key={i}>{w} </span>
                      )
                    )}
                  </h1>
                  <p>{meta.hint}</p>
                </div>
              </div>
            )
          })()}

          <main>
            {settingsOpen && <SettingsPanel onClose={() => setSettingsOpen(false)} />}
            {/* One lookup instead of a line per tab. A panel that serves more
                than one tab is given the props the registry recorded for it. */}
            {!settingsOpen && TABS.filter((entry) => entry.id === tab).map((entry) => (
              <entry.Component key={entry.id} {...(entry.takesMovie ? { movie } : {})} {...entry.props} />
            ))}
          </main>
        </>
      )}
      </div>
    </div>
  )
}

export default App
